services:
  zookeeper:
    image: zookeeper:3.9.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data
    networks:
      - pinot

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - pinot

  pinot-controller:
    image: apachepinot/pinot:1.4.0
    container_name: pinot-controller
    command: StartController -zkAddress zookeeper:2181
    environment:
      PINOT_FS_S3_ACCESS_KEY: admin
      PINOT_FS_S3_SECRET_KEY: admin123
      PINOT_FS_S3_ENDPOINT: http://minio:9000
      PINOT_FS_S3_USE_PATH_STYLE: true
    ports:
      - "9500:9000"
    depends_on:
      - zookeeper
    volumes:
      - pinot-controller-data:/opt/pinot/data
    networks:
      - pinot

  pinot-broker:
    image: apachepinot/pinot:1.4.0
    container_name: pinot-broker
    command: StartBroker -zkAddress zookeeper:2181
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks:
      - pinot

  pinot-server:
    image: apachepinot/pinot:1.4.0
    container_name: pinot-server
    command: StartServer -zkAddress zookeeper:2181
    depends_on:
      - pinot-controller
    volumes:
      - pinot-server-data:/opt/pinot/data
    networks:
      - pinot

  pinot-minion:
    image: apachepinot/pinot:1.4.0
    container_name: pinot-minion
    command: StartMinion -zkAddress zookeeper:2181
    environment:
      PINOT_FS_S3_ACCESS_KEY: admin
      PINOT_FS_S3_SECRET_KEY: admin123
      PINOT_FS_S3_ENDPOINT: http://minio:9000
      PINOT_FS_S3_USE_PATH_STYLE: "true"
    depends_on:
      - pinot-controller
      - minio
    networks:
      - pinot

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9400:9000"
      - "9401:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - pinot

volumes:
  zookeeper-data:
  pinot-controller-data:
  pinot-server-data:
  kafka-data:
  minio-data:

networks:
  pinot:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
